---
- name: Making base configuration
  hosts: all
  become: yes
  connection: local
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker repo key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repo
      apt_repository:
        repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable
        state: present

    - name: Install deployment dependencies
      apt:
        update_cache: yes
        allow_unauthenticated: yes
        name:
          - python3-pip
          - xz-utils
          - docker-ce 
          - docker-ce-cli 
          - containerd.io

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add Docker Compose to path
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
